#! bin/bash

printf "--" "-------------------------------------------------------------------------\n\n"
counter=4
zero=0
cat test_cases/gcc-trace.output | while read line
do
    if [[ $line == .* ]]; then
        echo $line
        $line
        printf "\n"
        let "counter-=1"
        if [ "$counter" -eq "$zero" ];then
            printf "--" "-------------------------------------------------------------------------\n\n"
            counter=4
        fi
    fi
done
